# Generated by Django 3.2.9 on 2021-12-10 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_detail', '0002_alter_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_detail_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message_detail.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ManyToManyField(related_name='author_id', through='message_detail.UserDetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
