# Generated by Django 3.2.9 on 2022-01-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_reply', '0004_remove_postreply_post'),
        ('posts', '0003_auto_20211213_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_reply',
            field=models.ManyToManyField(blank=True, related_name='post_reply', to='post_reply.PostReply'),
        ),
    ]
