# Generated by Django 3.2.9 on 2021-12-04 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
        ('message_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='message',
            field=models.ManyToManyField(blank=True, to='message_detail.Message'),
        ),
        migrations.AddField(
            model_name='chats',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
