# Generated by Django 3.2.9 on 2021-12-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='message',
            new_name='message_detail',
        ),
    ]
