# Generated by Django 3.2.9 on 2021-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='https://img1.pnghut.com/20/16/4/fR6d8RNp4R/smiley-happiness-watercolor-facial-expression-emoticon.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
