# Generated by Django 3.2.9 on 2021-12-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211213_0022'),
        ('post_reply', '0002_postreply_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post'),
        ),
    ]
