# Generated by Django 3.2.9 on 2021-12-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_reply', '0003_alter_postreply_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreply',
            name='post',
        ),
    ]
